### ISSUE TITLE
The running error in linux

### ISSUE THREAD

**Issue by Leno-B** [lartpang/PySODMetrics#1]
Traceback (most recent call last):
  File "test_metrics.py", line 29, in <module>
    FM.step(pred=pred, gt=mask)
  File "/usr/local/lib/python3.6/dist-packages/py_sod_metrics/sod_metrics.py", line 65, in step
    pred, gt = _prepare_data(pred, gt)
  File "/usr/local/lib/python3.6/dist-packages/py_sod_metrics/sod_metrics.py", line 21, in _prepare_data
    gt = gt > 128
TypeError: '>' not supported between instances of 'NoneType' and 'int'

How can I fix it?

**Comment by lartpang** [comment]
It means your `gt` is `None`.

Please check your settings and data.

**Comment by Leno-B** [comment]
> It means your `gt` is `None`.
> 
> Please check your settings and data.
> 
> In this code, the image loader is based on opencv.
> 
> When the data does not exist, it will return `None`.

I can run the setting in windows. However, the same setting can not run in Linux as the aforementioned error.

**Comment by Leno-B** [comment]
> > It means your `gt` is `None`.
> > Please check your settings and data.
> > In this code, the image loader is based on opencv.
> > When the data does not exist, it will return `None`.
> 
> I can run the setting in windows. However, the same setting can not run in Linux as the aforementioned error.

Thanks for your reply. I found the aforementioned error in Linux because of the file of **.ipynb_checkpoints**. I delete it and the code can run.
