### ISSUE TITLE
where is the test folder

### ISSUE THREAD

**Issue by ycyinchao** [lartpang/PySODMetrics#4]
![image](https://user-images.githubusercontent.com/105531816/184882876-0fd97344-87e8-48ad-b39b-79b1e309e314.png)

**Comment by ycyinchao** [comment]
ok,i got it!However, the results of my own evaluation of the model obtained by training sinet differ greatly from the baseline. Do you know why?
![image](https://user-images.githubusercontent.com/105531816/184890992-30a7cd0f-b3dc-4fbb-9646-71c6d071d6ac.png)

**Comment by lartpang** [comment]
@ycyinchao

> the results of my own evaluation of the model obtained by training sinet differ greatly from the baseline

Could you please list the results of the baseline model?

**Comment by ycyinchao** [comment]
> @ycyinchao
> 
> > the results of my own evaluation of the model obtained by training sinet differ greatly from the baseline
> 
> Could you please list the results of the baseline model?

![image](https://user-images.githubusercontent.com/105531816/185756480-0b2d4519-50c0-4bda-b80f-2f80f03c1280.png)
What I reproduced was this result. I didn't do anything. Why is the result better than his?

**Comment by lartpang** [comment]
Please make sure your training settings are consistent with the original paper's. 

And for more details, please ask in the issue of [SINet](https://github.com/DengPingFan/SINet/issues).

**Comment by ycyinchao** [comment]
> Please make sure your training settings are consistent with the original paper's.
> 
> And for more details, please ask in the issue of [SINet](https://github.com/DengPingFan/SINet/issues).

OK,and I would like to ask how this result is repeated? What are the training sets and test sets used?and Is the model used SINet?
![image](https://user-images.githubusercontent.com/105531816/185773086-bb640c8e-688b-4573-91a3-5ecd5f2b460e.png)

**Comment by lartpang** [comment]
@ycyinchao 

It is the result of these data: https://github.com/lartpang/PySODMetrics/tree/main/examples/test_data
