### ISSUE TITLE
where is the  (iv) training setting?I didn't find it in training settings

### ISSUE THREAD

**Issue by ycyinchao** [lartpang/PySODMetrics#5]
![image](https://user-images.githubusercontent.com/105531816/185754075-507eef9a-5f7e-455a-8929-4cbeeccdcf84.png)

**Comment by ycyinchao** [comment]
Does the （iv）training settings mean trained with the recommended
Parameter settings instead of data sets?If this is the case, why is it expressed by iv? It feels very ambiguous

**Comment by lartpang** [comment]
@ycyinchao 

Some details can be found at these issues:

- https://github.com/DengPingFan/SINet/issues/13
- https://github.com/DengPingFan/SINet/issues/9

**Comment by ycyinchao** [comment]
Thank you very much！！！
