### ISSUE TITLE
是否可以提供代码用于绘制PR曲线以及AUC曲线？

### ISSUE THREAD

**Issue by LYKlyk** [lartpang/PySODMetrics#6]

**Comment by lartpang** [comment]
@LYKlyk 

这个仓库主要是针对显著性检测等相关任务设计的，主要实现了更基础的数值指标。

对于绘图的话，您可以看看我的另一个仓库：https://github.com/lartpang/PySODEvalToolkit 这是基于这个指标仓库实现的。
其中提供了pr曲线的绘制。至于auc曲线，这个需要计算roc曲线，也就是 横坐标=FP/（FP+TN），纵坐标=TP/（TP+FN） 的曲线图。

目前我仅仅在PySODEvalToolkit中实现了PR曲线，这个PR曲线利用的就是指标库中统计的Precision和Recall绘制的。

如果您迫切需要的话，您可以参考我的指标实现进行二次开发。

**Comment by lartpang** [comment]
@LYKlyk 

我刚刚补充了FPR的实现，你实际上可以使用这里的FPR和Recall来实现ROC曲线（模仿PR曲线的方式）。

https://github.com/lartpang/PySODMetrics/commit/8f7e70ce4ca2ca1b991185869615ed5069687aa7#diff-399f8eb0cb6319d0282d6af8a02d6a2c225417c111b71e08becff2ec4a0d195cR162-R177
